29028 755219 陳柏希 三的倍數作業
nanshan-high-school/20200917-homework-basic pull request #11
Opened 2020-09-20 06:45 UTC by bradychen950410

請確認以下事項，並在中括號裡的空白改成 X 來選取項目：
* [x] 已閱讀 [作業繳交方式](https://hackmd.io/@nssh/nscsc/%2F%40nssh%2Fsummit-homework)
* [x] 在下方附上 Repl 連結
* [x] 檔案放在自己學號的目錄下
* [x] 標題以「班級座號、學號、姓名」作為開頭
* [x] 其他說明事項可以在下面補充

---

Repl 連結：https://repl.it/@BradyChen0410/multiple#main.cpp

2020-09-26 03:13 UTC, goodjack commented
請勿更動 pull_request_template.md 
這個檔案是設定發起 Pull Request 時候的預設文字 😅

2020-09-26 03:14 UTC, goodjack requested changes
排版縮排為 4 個空格

2020-09-26 03:14 UTC, goodjack commented on 755219/三的倍數.cpp
> +  if (num % 3 == 0){
右括號前有空格 跟第四行一樣

2020-09-27 22:51 UTC, kenny0515 commented
> 請勿更動 pull_request_template.md
> 這個檔案是設定發起 Pull Request 時候的預設文字

所以不用打勾勾嗎？

2020-09-27 23:08 UTC, bradychen950410 commented
> 請勿更動 pull_request_template.md
> 這個檔案是設定發起 Pull Request 時候的預設文字 😅

好喔

2024-10-04 07:38 UTC, closed without merging