homework submit
nanshan-high-school/20200917-homework-basic pull request #13
Opened 2020-09-20 11:43 UTC by wayne-1211

請確認以下事項，並在中括號裡的空白改成 X 來選取項目：
* [x] 已閱讀 [作業繳交方式](https://hackmd.io/@nssh/nscsc/%2F%40nssh%2Fsummit-homework)
* [x] 在下方附上 Repl 連結
* [x] 檔案放在自己學號的目錄下
* [x] 標題以「班級座號、學號、姓名」作為開頭
* [x] 其他說明事項可以在下面補充

---

Repl 連結：https://repl.it/@wayne1211/20200917HW#main.cpp

2020-09-27 10:33 UTC, goodjack requested changes

2020-09-27 10:33 UTC, goodjack commented on 755446/3_multiple.cpp
> +    {
這兩行的排版不對 請再調整一下

2020-09-27 12:54 UTC, wayne-1211 commented on 755446/3_multiple.cpp
> +    {
已更正

2020-09-28 02:48 UTC, goodjack commented
Well done!

2020-09-28 02:48 UTC, merged