29544 755466 謝奕宏
nanshan-high-school/20200917-homework-basic pull request #22
Opened 2020-09-22 11:49 UTC by Andy878787

29544 755466 謝奕宏

請確認以下事項，並在中括號裡的空白改成 X 來選取項目：
* [X] 已閱讀 [作業繳交方式](https://hackmd.io/@nssh/nscsc/%2F%40nssh%2Fsummit-homework)
* [X] 在下方附上 Repl 連結
* [X] 檔案放在自己學號的目錄下
* [X] 標題以「班級座號、學號、姓名」作為開頭
* [X] 其他說明事項可以在下面補充

---

Repl 連結：https://repl.it/@a755466/20200917#main.cpp

2020-09-26 04:02 UTC, goodjack requested changes

2020-09-26 04:02 UTC, goodjack commented on 755466/20200917.cpp
> +    if (num%3==0){
排版請修正

2020-09-30 14:38 UTC, Andy878787 commented
`#include <iostream>
using namespace std;
int main() {
    int num;
    cout << "請輸入數字:";
    cin >> num;

    if (num  % 3 == 0){
        cout << "是3的倍數\n";
    } else {
        cout << "不是3的倍數";
    }
} 
`

2020-09-30 14:38 UTC, Andy878787 commented
`
#include` <iostream>
using namespace std;
int main() {
    int num;
    cout << "請輸入數字:";
    cin >> num;

    if (num  % 3 == 0){
        cout << "是3的倍數\n";
    } else {
        cout << "不是3的倍數";
    }
} `

2020-09-30 14:38 UTC, closed without merging

2020-09-30 17:40 UTC, goodjack commented
怎麼關掉了？

2020-10-01 02:20 UTC, Andy878787 commented
不知道

2020-10-01 02:20 UTC, Andy878787 reviewed
#include <iostream>
using namespace std;
int main() {
    int num;
    cout << "請輸入數字:";
    cin >> num;

    if (num  % 3 == 0){
        cout << "是3的倍數\n";
    } else {
        cout << "不是3的倍數";
    }
}

2020-10-01 04:49 UTC, Andy878787 commented on 755466/20200917.cpp
> +    if (num%3==0){
#include <iostream>
using namespace std;
int main() {
    int num;
    cout << "請輸入數字:";
    cin >> num;

    if (num  % 3 == 0){
        cout << "是3的倍數\n";
    } else {
        cout << "不是3的倍數";
    }
}